### ISSUE TITLE
Disponibilizar link do repositório

### ISSUE THREAD

**Issue by CarlosValente93092** [CarlosValente93092/Projeto_Industrial#1]
git clone https://github.com/CarlosValente93092/Projeto_Industrial

**Comment by beacarvas** [comment]
oh men

**Comment by CarlosValente93092** [comment]
![image](https://user-images.githubusercontent.com/94235793/195302520-5bb8bdc5-b5d8-4eea-af8a-1cc8f3d8845c.png)

**Comment by FilipAntunes23** [comment]
Giro 🥇
