### ISSUE TITLE
Inception Presentation - Create Block Diagram

### ISSUE THREAD

**Issue by CarlosValente93092** [CarlosValente93092/Projeto_Industrial#26]
Link da drive para ficheiro .drawio:

https://uapt33090-my.sharepoint.com/personal/carlosvalente_ua_pt/_layouts/15/onedrive.aspx?ct=1663845637239&or=OWA%2DNT&cid=e016e523%2Db8c3%2Dcb29%2D8a7e%2D027f350fddb1&ga=1&id=%2Fpersonal%2Fcarlosvalente%5Fua%5Fpt%2FDocuments%2FPI%2FDiagramas

**Comment by GuilhermeCajeira** [comment]
![Image](https://user-images.githubusercontent.com/94262079/195981995-9f462203-32b4-401d-b396-7552868015b8.png)

**Comment by CarlosValente93092** [comment]
PI/Diagramas/

**Comment by CarlosValente93092** [comment]
Corrigir setinhas e adicioanr um espaço depois de "preta"
