### ISSUE TITLE
Escolha da Raspberry Pi (3 ou 4??)

### ISSUE THREAD

**Issue by dFernandes15** [CarlosValente93092/Projeto_Industrial#29]
https://www.tme.eu/pt/details/rpi-3b/computadores-uni-placa/raspberry-pi/raspberry-pi-3b/

Necessário decidir se a raspberry pi 3b com 1Gb de ram é suficiente ou se é necessária a raspberry pi 4 com 4 Gb de ram

**Comment by CarlosValente93092** [comment]
Ver Orange PI

**Comment by dFernandes15** [comment]
Não existe na Mouser, Mauser ou na TME... Existe na amazon mas não sei se é o melhor sítio de onde mandar vir

**Comment by CarlosValente93092** [comment]
É a que empresa fornecer
