### ISSUE TITLE
Fazer lista de inputs e outputs

### ISSUE THREAD

**Issue by CarlosValente93092** [CarlosValente93092/Projeto_Industrial#54]
Inputs:
RS485 (Communication CCS) (2 D)
EPO (Emergency Power Off) (1 A)
Relay 1 (A2) e relay 2 (Interlock) (CCS RELAY) (2 D)
LED RED, LED GREEN, LED BLUE (LEDS) (3 D)
12V, 12 V,5V (CCS POWER SUPPLYS) (3 A)
CP (1 A)

Outputs:
RS485 (2 D)
RB (1 D)
DB (1 D)
UPS (1 D)
CP (2 D)
12V e 5V
Temp (2 D)

5 ADC
16 Digital

**Comment by GuilhermeCajeira** [comment]
Sugeria meter isso num documento ou num bloco de notas e ficar guardado na drive
